spring:
  application:
    name: conference-demo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: true



# custom data-source
datasource:
  url: jdbc:postgresql://localhost:5432/conference_app
  username: postgres
  password: new_se3ret_password_test
  driverClassName: org.postgresql.Driver

# server information
server:
  port: 5000

# logging
logging:
  level:
    com: TRACE

# app details
app:
  version: 1.0.1
  endpoints:
    sessions: /api/v1/session
    speakers: /api/v1/speaker