spring:
  application:
    name: conference-demo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: true

# custom data-source
datasource:
  url: $JDBC_URL
  username: $JDBC_USERNAME
  password: $JDBC_PASSWORD
  driverClassName: org.postgresql.Driver

# server information
server:
  port: 80

# logging
logging:
  level:
    com: INFO