version: '3.7'

services:
    database:
      container_name: postgres-demo
      image: postgres
      environment:
        - POSTGRES_DB=conference_app
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=new_se3ret_password_test
      volumes:
        - ./:/sql_scripts
      ports:
        - 5432:5432
    adminer:
      container_name: adminer-demo
      image: adminer:latest
      restart: always
      ports:
        - 5001:8080